language: python
python:
  - "2.6"
  - "2.7"

# We need docker for our scripts that test various installations
services:
  - docker

# command to install dependencies
#install:
#  - "pip install -r dependencies"


env:
- TEST_SUITE=API
- TEST_SUITE=ALPINE
- TEST_SUITE=CENTOS
- TEST_SUITE=DEBIAN
- TEST_SUITE=FEDORA
- TEST_SUITE=FEATURE
- TEST_SUITE=OTHER
- TEST_SUITE=PYTHON
- TEST_SUITE=PACK
- TEST_SUITE=UBUNTU
# Some tests are with 2 docker that must run together. I hope it will be maintainable
- TEST_SUITE=DUO1


# command to run tests
script:
  - cd test
  - chmod a+x *sh
  - ./test_suite.sh


# specific call to launch coverage data into coveralls.io
#after_success:
#  coveralls