language: python
python:
  - "2.6"
  - "2.7"

# We need docker for our scripts that test various intallations
services:
  - docker

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - "pip install -r dependencies"
  - "pip install coveralls"
  - "pip install nose-cov"
  - "pip install unittest2"
# command to run tests
# notice: the nose-cov is used because it is compatible with --processes, but produce a .coverage by process
# so we must combine them in the end
script:
  - cd test
  - /bin/bash test_installation.sh
  - nosetests -xv --process-restartworker --processes=1 --process-timeout=999999999  --with-cov --cov=kunai
  - coverage combine
  - cd ..


# specific call to launch coverage data into coveralls.io
after_success:
  coveralls