language: python
python:
  - "2.6"
  - "2.7"

# We need docker for our scripts that test various installations
services:
  - docker

# command to install dependencies
#install:
#  - "pip install -r dependencies"


env:
- TEST_SUITE=API
- TEST_SUITE=ALPINE
- TEST_SUITE=AMAZONLINUX
- TEST_SUITE=CENTOS-6
- TEST_SUITE=CENTOS-7
- TEST_SUITE=DEBIAN
- TEST_SUITE=FEDORA
- TEST_SUITE=FEATURE
- TEST_SUITE=OTHER
- TEST_SUITE=OPENSUSE
- TEST_SUITE=PYTHON
- TEST_SUITE=PACK
- TEST_SUITE=UBUNTU
# Some tests are with 2 docker that must run together. I hope it will be maintainable
- TEST_SUITE=DUO1
# This one is with 3 containers, trying to join together
- TEST_SUITE=DUO2
# This one is with 4 containers, in 2 zones, one is sub level of another
- TEST_SUITE=DUO3
# This one is with 4 containers, in 3 zones, one is sub level of another
- TEST_SUITE=DUO4
# This is a full DEMO with 4 containers, for a distributed HTTP with
# 2 real servers
# 1 haproxy (generators to the 2 http)
# 1 customer, with DNS module
- TEST_SUITE=DEMO1


# command to run tests
script:
  - cd test
  - chmod a+x *sh
  - ./test_suite.sh


# specific call to launch coverage data into coveralls.io
#after_success:
#  coveralls