language: python
python:
  - "2.6"
  - "2.7"

# We need docker for our scripts that test various installations
services:
  - docker

# command to install dependencies
# some are only used for travis/coveralls so we are installing them here only
install:
  - "pip install -r dependencies"
  - "pip install coveralls"
  - "pip install nose-cov"
  - "pip install unittest2"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install ordereddict; fi

env:
- TEST_SUITE=CENTOS
- TEST_SUITE=DEBIAN
- TEST_SUITE=FEDORA
- TEST_SUITE=OTHER
- TEST_SUITE=PYTHON
- TEST_SUITE=UBUNTU


# command to run tests
# notice: the nose-cov is used because it is compatible with --processes, but produce a .coverage by process
# so we must combine them in the end
# * -x : stop at first error
# * --exe : allow to launch test py that are executable
# * --process : use 1 sub process
# * --process-timeout: at max 5min for a test to run
# * --process-resttartworker: one sub process by test, to avoid mix between libs
# NOTE: I don't kow why, byt process options are failing, with endless run
script:
  - cd test
  - chmod a+x *sh
  - ./test_suite.sh
#  - ./test_installation.sh
#  - nosetests -xv --processes=1 --process-timeout=300 --process-restartworker --with-cov --cov=kunai --exe
#  - coverage combine
#  - cd ..


# specific call to launch coverage data into coveralls.io
#after_success:
#  coveralls